# Generated by Django 5.0.2 on 2024-03-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_cart_product_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(to='shop.product'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
